name: Test building book and website

on:
  pull_request:

jobs:

  test-building-book-website:
    uses: ./.github/workflows/test-book-website.yml
    with:
      docker-image: ghcr.io/${{ github.repository }}:latest
