name: Test building book and website with default image

on:
  push:

jobs:
  test-building-book-website:
    uses: ./.github/workflows/test-book-website.yml
    with:
      docker-image: ghcr.io/${{ github.repository }}:latest
