name: Validate LaTeX Document
on: [ push, pull_request ]
jobs:
  test_building_book:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
      - name: Print dependency versions
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/hendricius/the-sourdough-framework:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            cd /app/book
            make show_tools_version
      - name: Print build variables
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/hendricius/the-sourdough-framework:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            cd /app/book
            make printvars
      - name: Test baking the release versions
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/hendricius/the-sourdough-framework:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            cd /app/book
            make -j build_serif_pdf build_ebook
